### ISSUE TITLE
Providing a minimalistic InSpec install guide

### ISSUE THREAD

**Issue by TheLonelyGhost** [mitre/inspec_install_guide#1]
More a question than anything. Why suggest the full ChefDK if only InSpec is being used from it? There is a curl-to-bash (and windows equivalent) for installing only the InSpec omnibus package, though it isn't very well documented, which I'd be happy to provide.

Net benefits of InSpec omnibus package over ChefDK:

- Only installing exactly what is needed
- InSpec is kept more up-to-date with the latest available version (ChefDK is notoriously behind in InSpec releases)
- Better granularity with installing a specific version of InSpec

I was about to submit a pull request to change the docs for these reasons, but wanted to ask the question first since it might make more sense in your situation to leave it as-is.

**Comment by aaronlippold** [comment]
Hi, originally this was put together just to centralize kind of our general
guidance. If there are multiple paths I'm happy to include them all as a
general set of guidance. Please feel free to put together a PR and I'm sure
we'll be happy to include it.

**Comment by aaronlippold** [comment]
@ejaronne you have been leading this communication with the customers. If you are in agreement I will push the PR.

**Comment by aaronlippold** [comment]
Merged and provided a few updates upon review by others
